import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Hello bro i a from header...</p>
        </header>
        {children}
        <footer>
          <p>Hello i am from footer...</p>
        </footer>
      </body>
    </html>
  )
}
